import type { NextPage } from 'next'
import Head from 'next/head'
import { ButtonWallet } from '../components/ButtonWallet'
import { Footer, Header, Main, Page } from '../components/Common'
import { GridGif } from '../components/GridGIF'
import { SideBar } from '../components/SideBar'
import { BrandName, TextFooter, TextURL } from '../components/Text'

const GIF_LIST = [
  'https://i.giphy.com/media/eIG0HfouRQJQr1wBzz/giphy.webp',
	'https://media3.giphy.com/media/L71a8LW2UrKwPaWNYM/giphy.gif',
	'https://media4.giphy.com/media/AeFmQjHMtEySooOc8K/giphy.gif',
	'https://i.giphy.com/media/PAqjdPkJLDsmBRSYUp/giphy.webp',
  'https://i.giphy.com/media/eIG0HfouRQJQr1wBzz/giphy.webp',
	'https://media3.giphy.com/media/L71a8LW2UrKwPaWNYM/giphy.gif',
	'https://media4.giphy.com/media/AeFmQjHMtEySooOc8K/giphy.gif',
	'https://i.giphy.com/media/PAqjdPkJLDsmBRSYUp/giphy.webp',
]

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <BrandName/>
        <ButtonWallet/>
      </Header>
      <Main>
        <SideBar/>
        <GridGif gifList={GIF_LIST}/>
      </Main>
      <Footer>
        <TextFooter>Made with ❤️ by <TextURL href='https://twitter.com/BerzanXYZ'>@BerzanXYZ</TextURL></TextFooter>
      </Footer>
    </Page>
  )
}

export default Home
