import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Header, Main, Page } from '../components/Common'
import { BrandName, TextFooter, TextURL } from '../components/Text'

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <BrandName/>
      </Header>

      <Main>

      </Main>

      <Footer>
        <TextFooter>Made with ❤️ by <TextURL href='https://twitter.com/BerzanXYZ'>@BerzanXYZ</TextURL></TextFooter>
      </Footer>
    </Page>
  )
}

export default Home
