import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Header, Main, Page } from '../components/Common'

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        
      </Header>

      <Main>

      </Main>

      <Footer>

      </Footer>
    </Page>
  )
}

export default Home
